/* Dashboard CCM/VDF: estado de interfaz y renderizado. Sin dependencias. */
'use strict';
const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const esc = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
const icon = name => `<svg class="icon" aria-hidden="true"><use href="#i-${name}"/></svg>`;
const normalize = value => String(value).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
const offers = { unreviewed: ['Sin revisar', 'slate'], firm: ['Oferta firme', 'green'], reference: ['Referencial', 'amber'], blocked: ['Bloqueado', 'red'], review: ['Revisión especial', 'blue'] };
const checkStates = { unreviewed: ['Sin revisar', 'slate'], available: ['Disponible', 'green'], missing: ['Falta', 'red'], partial: ['Parcial', 'amber'], conflict: ['Contradicción', 'red'], not_applicable: ['No aplica', 'slate'] };
const outcomes = { sent: 'Propuesta enviada', won: 'Adjudicado', lost: 'No adjudicado', cancelled: 'Cancelado', completed: 'Finalizado' };
const infoLabels = { client: 'Cliente final', buyer: 'Comprador / EPC', name: 'Proyecto', crm: 'ID CRM', location: 'Ubicación', manager: 'Responsable', driveUrl: 'Carpeta de Drive', startDate: 'Fecha de ingreso', targetDate: 'Fecha objetivo', technology: 'Solución', offerStatus: 'Condición de oferta', offerReason: 'Criterio de oferta' };
let store;
let startupError = '';
try { store = CCMStorage.create(localStorage); } catch { startupError = 'El navegador no permite almacenar proyectos. Habilita el almacenamiento para trabajar con esta cartera.'; }
const state = { projects: [], selectedId: null, tab: 'diagnosis', search: '', status: '', lifecycle: 'active', pillar: '', section: '', checkState: '', checkSearch: '', page: 1, queryFilter: 'open', actor: 'Usuario local', formContext: null, pendingImport: null, review: null, fileMessage: '', startupErrors: [] };
try { state.actor = localStorage.getItem('ccm-vdf.actor') || state.actor; } catch { /* Se informa con startupError. */ }
const project = () => state.projects.find(entry => entry.id === state.selectedId);
const closed = value => value?.lifecycle.status === 'closed';
const formatDate = value => value && CCM.validDate(value) ? new Intl.DateTimeFormat('es-CL', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${value}T12:00:00Z`)) : 'Sin definir';
const formatTime = value => value && CCM.validInstant(value) ? new Intl.DateTimeFormat('es-CL', { dateStyle: 'short', timeStyle: 'short', timeZone: 'America/Santiago' }).format(new Date(value)) : 'Sin fecha';
const badge = (label, tone = 'slate') => `<span class="status-badge tone-${tone}"><span class="status-dot"></span>${esc(label)}</span>`;
const offerBadge = value => closed(value) ? badge('Cerrado', 'slate') : badge(...offers[value.info.offerStatus]);
const empty = message => `<p class="empty-state">${esc(message)}</p>`;
const link = (url, label) => CCM.safeURL(url) ? `<a href="${esc(CCM.safeURL(url))}" target="_blank" rel="noopener noreferrer">${esc(label)} ${icon('external')}</a>` : esc(label);
const actionButton = (action, label, recordId = '', className = 'button') => `<button type="button" class="${className}" data-action="${action}"${recordId ? ` data-id="${esc(recordId)}"` : ''}>${label}</button>`;
const editableButton = (action, label, recordId = '') => closed(project()) ? '' : actionButton(action, label, recordId);

function loadProjects() {
  if (!store) return;
  const result = store.list(); state.projects = result.projects; state.startupErrors = result.errors;
  if (!project()) state.selectedId = state.projects[0]?.id || null;
}
function renderStorage() {
  $('#storage-status').textContent = startupError ? 'Almacenamiento no disponible' : store?.connected ? `Carpeta: ${store.directoryName} · guardado y recarga automáticos` : 'Vincula la carpeta projects para actualizar con tu agente';
  $('#save-all').hidden = !store?.connected;
  const messages = [startupError, ...state.startupErrors, state.fileMessage, ...(store?.errors || [])].filter(Boolean);
  $('#storage-alert').hidden = !messages.length; $('#storage-alert').textContent = [...new Set(messages)].join(' ');
  $('.profile-copy strong').textContent = state.actor; $('.profile-copy small').textContent = 'Responsable de cambios';
  $('#profile-popover').innerHTML = `<strong>${esc(state.actor)}</strong><span>Responsable de cambios</span>${actionButton('identity', 'Cambiar nombre')}`;
}
function renderKPIs() {
  const active = state.projects.filter(value => !closed(value));
  const cards = [{ value: active.length, label: 'Negocios activos', caption: `${state.projects.filter(closed).length} proyectos cerrados`, tone: 'green', icon: 'briefcase', status: '' }, ...[['firm', 'Listos para oferta firme', 'document'], ['reference', 'Oferta referencial', 'document'], ['blocked', 'Bloqueados', 'lock'], ['review', 'Revisión especial', 'search']].map(([status, label, symbol]) => ({ value: active.filter(value => value.info.offerStatus === status).length, label, tone: offers[status][1], icon: symbol, status }))];
  $('#kpi-grid').innerHTML = cards.map(card => `<button class="kpi-card tone-${card.tone}${card.status && state.status === card.status ? ' is-filtered' : ''}" data-status="${card.status}" aria-pressed="${state.status === card.status}" aria-label="${card.value} ${card.label}. Filtrar cartera"><span class="kpi-icon">${icon(card.icon)}</span><span class="kpi-copy"><span class="kpi-value">${card.value}</span><span class="kpi-label">${card.label}</span><span class="kpi-caption">${card.caption || `${active.length ? Math.round(card.value / active.length * 100) : 0}% de la cartera activa`}</span></span><span class="mini-bars" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></span></button>`).join('');
}
function daysMarkup(value) {
  const calculation = CCM.elapsed(value);
  if (!calculation) return '<span class="muted">Sin inicio</span>';
  return `<span class="days-value${calculation.complete ? '' : ' incomplete'}" title="${calculation.complete ? calculation.frozen ? 'Duración congelada al cierre' : 'Excluye el día de inicio, sábados, domingos y feriados registrados' : `Calendario pendiente para ${calculation.missingYears.join(', ')}`}">${calculation.days}${calculation.complete ? '' : '*'}${calculation.frozen ? ` ${icon('lock')}` : ''}</span>`;
}
function renderProjects() {
  const query = normalize(state.search.trim());
  const filtered = state.projects.filter(value => {
    const content = normalize([value.info.client, value.info.name, value.info.crm, ...value.documents.flatMap(doc => [doc.name, doc.path])].join(' '));
    return (!query || content.includes(query)) && (!state.status || value.info.offerStatus === state.status) && (state.lifecycle === 'all' || (state.lifecycle === 'closed') === closed(value));
  });
  $('#project-count').textContent = `${filtered.length} ${filtered.length === 1 ? 'proyecto' : 'proyectos'}`; $('#lifecycle-filter').value = state.lifecycle;
  $('#no-projects').hidden = Boolean(filtered.length); $('#no-projects').textContent = state.projects.length ? 'No hay proyectos que coincidan con los filtros.' : 'Tu cartera está vacía. Crea un proyecto o importa su JSON para comenzar.';
  $('#project-rows').innerHTML = filtered.map(value => {
    const advance = CCM.progress(value), pending = CCM.blockers(value).length;
    return `<tr data-project="${esc(value.id)}" class="${value.id === state.selectedId ? 'selected' : ''}"><td><button class="project-name-button" data-select-project="${esc(value.id)}" aria-pressed="${value.id === state.selectedId}">${esc(value.info.client || 'Sin cliente')}</button></td><td class="project-name-cell" title="${esc(value.info.name)}">${esc(value.info.name || 'Sin nombre')}</td><td><div class="progress-cell tone-${offers[value.info.offerStatus][1]}"><span class="progress-value">${advance === null ? 'N/A' : advance + '%'}</span><span class="progress-track"><span class="progress-fill" style="width:${advance || 0}%"></span></span></div></td><td>${offerBadge(value)}</td><td class="${pending ? 'danger-text' : ''}" title="Controles críticos pendientes de verificación">${pending}</td><td>${value.queries.filter(item => item.status === 'open').length}</td><td>${daysMarkup(value)}</td><td>${formatDate(value.info.targetDate)}</td><td><button class="icon-button row-menu" data-action="project-options" data-id="${esc(value.id)}" aria-label="Opciones de ${esc(value.info.name)}">${icon('more')}</button></td></tr>`;
  }).join('');
}
function renderOverview() {
  const value = project(); $('.project-tabs').hidden = !value;
  if (!value) {
    $('#project-overview').innerHTML = `<div class="project-welcome"><span class="welcome-icon">${icon('project')}</span><div><h2 id="selected-project-title">Cada proyecto, su propia historia</h2><p>Comienza con los 145 controles sin revisar. Conserva evidencias, consultas y revisiones en un solo JSON por proyecto.</p></div></div>`;
    $('#project-workflow-bar').innerHTML = `${actionButton('new-project', `${icon('plus')} Crear primer proyecto`, '', 'button button-primary')}${actionButton('import', 'Importar un proyecto')}`;
    $('#project-panel').innerHTML = `<div class="welcome-steps"><div><b>1</b><strong>Crea el proyecto</strong><p>Registra sus datos de ingreso y la carpeta con antecedentes.</p></div><div><b>2</b><strong>Revisa y encuentra evidencia</strong><p>Completa controles manualmente o importa una revisión de tu chat.</p></div><div><b>3</b><strong>Conserva la trazabilidad</strong><p>Registra cambios, resuelve consultas y archiva el cierre.</p></div></div>`;
    return;
  }
  $('#project-overview').innerHTML = `<img class="project-image" src="assets/mine.jpg" alt="Imagen referencial de una faena minera"><div class="project-info"><div class="project-title-line"><h2 id="selected-project-title">${esc(value.info.client || 'Sin cliente')} – ${esc(value.info.name || 'Sin nombre')}</h2>${offerBadge(value)}</div><div class="project-metadata"><div class="metadata-item"><span class="metadata-label">Responsable</span><span class="metadata-value">${esc(value.info.manager || 'Sin asignar')}</span></div><div class="metadata-item"><span class="metadata-label">Ubicación</span><span class="metadata-value">${esc(value.info.location || 'Sin definir')}</span></div><div class="metadata-item"><span class="metadata-label">Fecha objetivo</span><span class="metadata-value">${formatDate(value.info.targetDate)}</span></div><div class="metadata-item"><span class="metadata-label">${closed(value) ? 'Duración al cierre' : 'Días hábiles transcurridos'}</span><span class="metadata-value">${daysMarkup(value)}</span></div></div></div><div class="project-header-actions">${actionButton('export', `${icon('document')} JSON`)}<button class="icon-button" data-action="project-options" data-id="${esc(value.id)}" aria-label="Opciones del proyecto">${icon('more')}</button></div>`;
  $('#project-workflow-bar').innerHTML = `<span class="version-label">${closed(value) ? `${icon('lock')} Cerrado el ${formatDate(value.lifecycle.closure.date)}` : `Ingreso: ${formatDate(value.info.startDate)}`} <span>· JSON v${value.version}</span></span><div>${closed(value) ? actionButton('reopen-project', 'Reabrir proyecto') : `${actionButton('ai-workflow', `${icon('search')} Revisión con IA`, '', 'button button-primary')}${actionButton('edit-project', 'Editar proyecto')}${actionButton('close-project', 'Cerrar propuesta')}`}</div>`;
  $('#tab-queries').textContent = `Consultas (${value.queries.filter(query => query.status === 'open').length})`;
}
function evidenceMarkup(entries) {
  if (!entries.length) return '<span class="muted">Sin evidencia registrada.</span>';
  return entries.map(entry => `<article class="evidence-card"><div class="evidence-top"><strong>${icon('document')} ${entry.url ? link(entry.url, entry.fileName) : esc(entry.fileName)}</strong>${entry.revision ? badge(`Rev. ${entry.revision}`, 'blue') : ''}</div><p class="evidence-location">${esc(entry.path || entry.fileName)} · ${esc(entry.locator)}</p><blockquote>${esc(entry.quote)}</blockquote></article>`).join('');
}
function renderDiagnosis() {
  const value = project();
  const cards = CCM.catalog.pillars.map(pillar => {
    const items = value.checklist.filter(item => item.pillar === pillar.id), advance = CCM.progress(value, pillar.id), reviewed = items.some(item => item.state !== 'unreviewed'), critical = items.some(item => item.critical && ['missing', 'conflict'].includes(item.state));
    const tone = advance === 100 ? 'green' : critical ? 'red' : reviewed ? 'amber' : 'slate', label = advance === null ? 'No aplica' : advance === 100 ? 'Completo' : critical ? 'Crítico' : reviewed ? 'En revisión' : 'Sin revisar';
    return `<button class="pillar-card tone-${tone}${String(pillar.id) === state.pillar ? ' is-filtered' : ''}" data-pillar="${pillar.id}" aria-pressed="${String(pillar.id) === state.pillar}"><div class="pillar-title">${icon(pillar.icon)}<h3>${pillar.id}. ${esc(pillar.title)}</h3></div><div class="pillar-ring" style="--progress:${advance || 0}"><span>${advance === null ? 'N/A' : advance + '%'}</span></div><span class="pillar-status"><span class="status-dot"></span>${label}</span></button>`;
  }).join('');
  const filtered = value.checklist.filter(item => (!state.pillar || String(item.pillar) === state.pillar) && (!state.section || String(item.section) === state.section) && (!state.checkState || item.state === state.checkState) && (!state.checkSearch || normalize(`${item.label} ${item.value} ${item.notes}`).includes(normalize(state.checkSearch))));
  const pageCount = Math.max(1, Math.ceil(filtered.length / 15)); state.page = Math.min(state.page, pageCount);
  const visible = filtered.slice((state.page - 1) * 15, state.page * 15);
  return `<div class="pillars-grid">${cards}</div><div class="section-heading checklist-heading"><div class="heading-with-count"><h2>Checklist de diagnóstico</h2><span class="count-pill">${filtered.length} de ${value.checklist.length} ítems</span></div><a class="guide-link" href="assets/Requerimientos_minimos_CCM_VDF.pdf" target="_blank" rel="noopener">Ver guía ${icon('external')}</a></div><div class="checklist-filters"><label>${icon('search')}<input id="checklist-search" type="search" aria-label="Buscar un control" value="${esc(state.checkSearch)}" placeholder="Buscar un control…"></label><select id="section-filter" aria-label="Filtrar por sección"><option value="">Todas las secciones</option>${Object.entries(CCM.catalog.sections).map(([key, label]) => `<option value="${key}"${state.section === key ? ' selected' : ''}>${key}. ${esc(label)}</option>`).join('')}</select><select id="check-state-filter" aria-label="Filtrar por estado"><option value="">Todos los estados</option>${Object.entries(checkStates).map(([key, [label]]) => `<option value="${key}"${state.checkState === key ? ' selected' : ''}>${label}</option>`).join('')}</select>${state.pillar ? actionButton('reset-checklist', 'Quitar filtro de pilar', '', 'text-button') : ''}</div><div class="table-scroll"><table class="checklist-table live-checklist"><thead><tr><th>Ítem</th><th>Sección</th><th>Estado</th><th>Crítico</th><th>Valor / origen</th><th><span class="sr-only">Editar o ver</span></th></tr></thead><tbody id="checklist-rows">${visible.map(item => `<tr><td>${actionButton('checklist', esc(item.label), item.id, 'item-name-button')}<small class="item-id">${esc(item.id)}</small></td><td>${esc(CCM.catalog.sections[item.section])}</td><td>${badge(...checkStates[item.state])}${item.manualLock ? '<small class="manual-label">Protegido manualmente</small>' : ''}</td><td>${item.critical ? `<span class="${['available', 'not_applicable'].includes(item.state) ? 'muted' : 'danger-text'}">Sí</span>` : 'No'}</td><td><span class="item-value">${esc(item.value || '—')}</span>${item.evidence.length ? actionButton('evidence', `${icon('document')} ${item.evidence.length} ${item.evidence.length === 1 ? 'fuente' : 'fuentes'}`, item.id, 'evidence-link') : '<small class="muted">Sin evidencia</small>'}</td><td><button class="icon-button" data-action="checklist" data-id="${esc(item.id)}" aria-label="Ver ${esc(item.label)}">${icon('chevron')}</button></td></tr>`).join('')}</tbody></table></div>${visible.length ? '' : empty('No hay controles que coincidan con los filtros.')}<div class="pagination"><span>Disponibles / aplicables. «No aplica» se excluye del avance.</span><div>${actionButton('previous-page', 'Anterior')}<span>${state.page} / ${pageCount}</span>${actionButton('next-page', 'Siguiente', String(pageCount))}</div></div>`;
}
function renderSummary() {
  const value = project(), calculation = CCM.elapsed(value), pending = CCM.blockers(value), coverage = value.analysis.coverage;
  return `<div class="tab-content"><div class="panel-heading"><h3>Resumen del proyecto</h3>${actionButton('calendar', `${icon('calendar')} Feriados de Chile`)}</div><div class="summary-grid"><dl class="summary-box"><dt>${closed(value) ? 'Días hábiles al cierre' : 'Días hábiles transcurridos'}</dt><dd>${daysMarkup(value)}</dd><p>Desde el día siguiente al ingreso.${calculation && !calculation.complete ? ` <strong>Conteo provisional: verifica ${calculation.missingYears.join(', ')}.</strong>` : ''}</p></dl><dl class="summary-box"><dt>Avance del diagnóstico</dt><dd>${CCM.progress(value) ?? 'N/A'}${CCM.progress(value) === null ? '' : '%'}</dd><p>${value.checklist.filter(item => item.state === 'available').length} disponibles · ${value.checklist.filter(item => item.state === 'not_applicable').length} no aplican.</p></dl><dl class="summary-box"><dt>Controles críticos pendientes</dt><dd>${pending.length}</dd><p>${pending.length ? 'Requieren verificación antes de una oferta firme.' : 'Sin controles críticos pendientes.'}</p></dl><dl class="summary-box"><dt>Consultas</dt><dd>${value.queries.filter(query => query.status === 'open').length} abiertas</dd><p>${value.queries.filter(query => query.status === 'closed').length} cerradas con resolución.</p></dl></div><dl class="project-facts">${['buyer', 'crm', 'manager', 'location', 'startDate', 'targetDate', 'offerReason'].map(key => `<div><dt>${infoLabels[key]}</dt><dd>${esc(key.endsWith('Date') ? formatDate(value.info[key]) : value.info[key] || 'Sin definir')}</dd></div>`).join('')}<div><dt>Carpeta de antecedentes</dt><dd>${value.info.driveUrl ? link(value.info.driveUrl, 'Abrir en Drive') : 'Sin vincular'}</dd></div></dl><div class="coverage-box"><h3>Última revisión de antecedentes</h3>${value.reviews.length ? `<p>${esc(value.analysis.provider || 'IA externa')} · ${formatTime(value.analysis.reviewedAt)} · ${coverage.read} de ${coverage.discovered} archivos leídos en esta revisión · ${coverage.reused || 0} reutilizados.</p><p>${esc(value.analysis.summary)}</p><p>${esc(coverage.notes)}</p>${coverage.unreadable.length ? `<p class="danger-text">No leídos: ${coverage.unreadable.map(esc).join(', ')}</p>` : ''}` : '<p>Aún no se ha importado una revisión de IA. Un enlace de Drive no acredita que sus archivos hayan sido leídos.</p>'}</div>${closed(value) ? `<div class="closure-summary"><h3>${esc(outcomes[value.lifecycle.closure.outcome] || 'Proyecto cerrado')}</h3><p>${esc(value.lifecycle.closure.reason)}</p><p>Cerrado por ${esc(value.lifecycle.closure.actor)} el ${formatDate(value.lifecycle.closure.date)}. Duración y calendario conservados en el JSON.</p></div>` : ''}</div>`;
}
function renderFileRegistry() {
  const value=project(),count=CCMFiles.summary(value);
  const statuses={pending:'Pendiente',processed:'Lectura completa',partial:'Lectura parcial',failed:'Error de lectura'};
  return `<section class="file-registry"><div class="panel-heading"><h3>Archivos procesados en Drive</h3>${editableButton('file-form',`${icon('plus')} Registrar archivo`)}</div><p class="panel-description">${value.info.driveUrl?link(value.info.driveUrl,'Carpeta de antecedentes'):'Define la carpeta de Drive en «Editar proyecto».'} · Inventario conservado en el JSON. Antes de omitir una lectura, el chat debe actualizar los metadatos de la carpeta.</p><div class="file-counts"><span><strong>${count.total}</strong> registrados</span><span><strong>${count.processed}</strong> con lectura completa</span><span><strong>${count.skip}</strong> sin cambios registrados</span><span><strong>${count.read+count.verify}</strong> por leer / verificar</span><span><strong>${count.unavailable}</strong> no disponibles</span></div>${count.total?`<div class="table-scroll file-table-scroll"><table class="file-table"><thead><tr><th>Archivo / ruta</th><th>Última lectura</th><th>Próxima revisión</th><th>Acciones</th></tr></thead><tbody>${value.processedFiles.map(file=>{const decision=CCMFiles.evaluate(file,value.info.driveUrl);return `<tr><td><strong>${file.url?link(file.url,file.fileName):esc(file.fileName)}</strong><small>${esc(file.path)}</small><small>ID Drive: ${esc(file.driveFileId||'No disponible')}</small><small>Inventariado: ${formatTime(file.lastSeenAt)}</small></td><td>${esc(statuses[file.processing.status])}<small>${formatTime(file.processing.processedAt)}</small><small>${esc(file.processing.provider)}</small></td><td>${badge(decision.label,decision.action==='skip'?'green':decision.action==='unavailable'?'slate':'amber')}<small>${esc(decision.reason)}</small></td><td>${actionButton('file-details','Ver',file.id)}${editableButton('file-form','Editar',file.id)}${!closed(value)&&!file.processing.forceReview?editableButton('file-reread','Solicitar relectura',file.id):''}</td></tr>`;}).join('')}</tbody></table></div>`:empty('Aún no hay archivos procesados registrados. La próxima revisión IA puede crear el inventario con rutas, metadatos y resultados de lectura.')}</section>`;
}
function renderDocuments() {
  const value = project();
  return `<div class="tab-content"><div class="panel-heading"><h3>Documentos y correos</h3>${editableButton('document-form', `${icon('plus')} Registrar documento`)}</div><p class="panel-description">Cada archivo y revisión tiene su propio registro. Los originales se mantienen en su carpeta; el JSON conserva las referencias.</p>${value.documents.length ? value.documents.map(doc => `<div class="document-row">${icon('document')}<div><strong>${doc.url ? link(doc.url, doc.name) : esc(doc.name)}</strong><p>${esc(doc.path || 'Sin ruta')} ${doc.revision ? `· Rev. ${esc(doc.revision)}` : ''}</p><p>${esc(doc.notes)}</p></div>${badge(({read:'Leído',unreadable:'No se pudo leer',metadata_only:'Solo metadatos',not_reviewed:'Sin revisar'})[doc.readStatus], doc.readStatus === 'read' ? 'green' : 'slate')}${editableButton('document-form', 'Editar', doc.id)}</div>`).join('') : empty('Aún no hay documentos registrados. Agrega sus referencias o importa el inventario de la revisión IA.')}<div class="panel-heading separated"><h3>Historial entre revisiones</h3>${editableButton('revision-form', `${icon('plus')} Registrar cambio`)}</div>${value.revisions.length ? value.revisions.map(revision => `<article class="revision-card"><div class="panel-heading"><h4>${esc(revision.familyId)} <span class="revision-route">${esc(revision.fromRevision)} → ${esc(revision.toRevision)}</span></h4>${badge(({documented:'Motivo documentado',inferred:'Motivo inferido',unknown:'Motivo no encontrado'})[revision.justificationStatus], revision.justificationStatus === 'documented' ? 'green' : 'amber')}</div><p><strong>Cambios:</strong> ${esc(revision.summary)}</p><p><strong>Justificación:</strong> ${esc(revision.justification || 'No encontrada en los antecedentes.')}</p><p><strong>Impacto:</strong> ${esc(revision.impact || 'No determinado.')}</p>${evidenceMarkup(revision.evidence)}${editableButton('revision-form', 'Editar registro', revision.id)}</article>`).join('') : empty('Sin comparaciones registradas. Las revisiones de propuestas son independientes de la versión del JSON.')}</div>`;
}
function renderQueries() {
  const value = project(), filtered = value.queries.filter(query => state.queryFilter === 'all' || query.status === state.queryFilter);
  return `<div class="tab-content"><div class="panel-heading"><h3>Consultas y resoluciones</h3>${editableButton('query-form', `${icon('plus')} Nueva consulta`)}</div><div class="segmented" aria-label="Filtrar consultas">${[['open','Abiertas'],['closed','Cerradas'],['all','Todas']].map(([key,label]) => `<button data-query-filter="${key}" class="${state.queryFilter === key ? 'active' : ''}" aria-pressed="${state.queryFilter === key}">${label} <span>${value.queries.filter(query => key === 'all' || query.status === key).length}</span></button>`).join('')}</div>${filtered.length ? filtered.map(query => `<article class="query-card"><div class="panel-heading"><h4>${esc(query.title)}</h4>${badge(query.status === 'open' ? 'Abierta' : 'Cerrada', query.status === 'open' ? 'amber' : 'green')}</div><p>${esc(query.question)}</p><p class="muted">${esc(query.assignedTo || 'Sin responsable asignado')} · ${formatTime(query.createdAt)} · ${query.messages.length} seguimientos</p>${query.status === 'closed' ? `<p class="resolution-preview"><strong>Resolución:</strong> ${esc(query.resolution)}</p>` : ''}${actionButton('query-detail', 'Ver seguimiento', query.id)}</article>`).join('') : empty('No hay consultas en este estado.')}</div>`;
}
function renderTeam() {
  return `<div class="tab-content"><div class="panel-heading"><h3>Equipo y contactos</h3>${editableButton('team-form', `${icon('plus')} Agregar integrante`)}</div>${project().team.length ? `<div class="team-grid">${project().team.map(person => `<article class="contact-card"><div class="contact-avatar">${esc(person.name.split(/\s+/).map(part => part[0]).slice(0,2).join(''))}</div><h4>${esc(person.name)}</h4><p>${esc(person.role || 'Sin cargo')} · ${esc(person.company || 'Sin empresa')}</p><p>${esc(person.phone || 'Sin teléfono')}</p><p>${esc(person.email || 'Sin correo')}</p><p class="muted">${esc(person.notes)}</p>${editableButton('team-form','Editar',person.id)}</article>`).join('')}</div>` : empty('El proyecto aún no tiene integrantes. Registra nombre, cargo, empresa, teléfono y correo.')}</div>`;
}
const eventTitle = event => ({'project.created':'Proyecto creado','project.updated':'Datos actualizados','checklist.updated':'Checklist actualizado','documents.updated':'Documento registrado / actualizado','processedFiles.updated':'Registro de lectura actualizado','revisions.updated':'Cambio entre revisiones','queries.updated':'Consulta registrada','team.updated':'Equipo actualizado','query.message':'Seguimiento agregado','query.closed':'Consulta resuelta','query.reopened':'Consulta reabierta','note.added':'Registro manual','calendar.updated':'Calendario actualizado','project.closed':'Propuesta cerrada','project.reopened':'Proyecto reabierto','ai.reviewed':'Revisión IA procesada'})[event.kind] || event.kind;
function renderHistory() {
  return `<div class="tab-content"><div class="panel-heading"><h3>Historial y decisiones</h3>${editableButton('note-form', `${icon('plus')} Agregar registro`)}</div>${[...project().history].reverse().map(event => `<article class="history-event"><div class="panel-heading"><h4>${esc(eventTitle(event))}</h4><time>${formatTime(event.at)}</time></div><p>${esc(event.reason)}</p><p class="muted">${esc(event.actor)} · ${event.origin === 'ai_automation' ? 'Actualización automática de IA' : event.origin === 'ai_review' ? 'IA revisada por una persona' : 'Registro manual'}</p><details><summary>Ver valores anteriores y nuevos</summary>${event.changes.map(change => `<div class="history-change"><strong>${esc(change.path)}</strong><div class="diff-grid"><div><span>Anterior</span><pre>${esc(JSON.stringify(change.before,null,2))}</pre></div><div><span>Nuevo</span><pre>${esc(JSON.stringify(change.after,null,2))}</pre></div></div></div>`).join('')}</details></article>`).join('')}</div>`;
}
function renderPanel() {
  if (!project()) return;
  $$('.tab').forEach(tab => { const active = tab.dataset.tab === state.tab; tab.classList.toggle('active',active); tab.setAttribute('aria-selected',String(active)); tab.tabIndex = active ? 0 : -1; });
  $('#project-panel').setAttribute('aria-labelledby',`tab-${state.tab}`);
  $('#project-panel').innerHTML = (state.tab==='documents'?renderFileRegistry():'')+({diagnosis:renderDiagnosis,summary:renderSummary,documents:renderDocuments,queries:renderQueries,team:renderTeam,history:renderHistory})[state.tab]();
}
function renderSidebarPanels() {
  const queries = state.projects.filter(value => !closed(value)).flatMap(value => value.queries.filter(query => query.status === 'open').map(query => ({ value, query })));
  $('#action-count').textContent = queries.length;
  $('#action-list').innerHTML = queries.slice(0,4).map(({value,query}) => `<button class="action-item tone-amber" data-open-query="${esc(query.id)}" data-owner="${esc(value.id)}"><span class="action-icon">${icon('alert')}</span><span class="action-copy"><strong>${esc(query.title)}</strong><small>${esc(value.info.client)} – ${esc(value.info.name)}</small></span>${icon('chevron')}</button>`).join('') || empty('Sin consultas abiertas. Los faltantes y sus consultas se registran al revisar cada proyecto.');
  const events = state.projects.flatMap(value => value.history.map(event => ({value,event}))).sort((a,b) => b.event.at.localeCompare(a.event.at)).slice(0,5);
  $('#activity-list').innerHTML = events.map(({value,event}) => `<div class="activity-item"><span class="activity-icon tone-${event.origin.startsWith('ai_') ? 'blue' : 'green'}">${icon(event.kind.includes('query') ? 'chat' : event.kind.includes('closed') ? 'lock' : 'document')}</span><div class="activity-copy"><div class="activity-topline"><strong>${esc(eventTitle(event))}</strong><time>${formatTime(event.at)}</time></div><p>${esc(value.info.name || 'Proyecto')} · ${esc(event.actor)}</p></div></div>`).join('') || empty('Los cambios guardados aparecerán aquí.');
  $('.notification-count').textContent = queries.length; $('.notification-count').hidden = !queries.length; $('#notifications-button').setAttribute('aria-label',`${queries.length} consultas pendientes`);
  $('#notifications-popover').innerHTML = `<strong>Consultas pendientes</strong>${queries.slice(0,5).map(({value,query}) => `<button class="notification-entry" data-open-query="${esc(query.id)}" data-owner="${esc(value.id)}">${esc(query.title)}<small>${esc(value.info.client)}</small></button>`).join('') || empty('Sin consultas pendientes.')}`;
}
function renderAll() { renderStorage(); renderKPIs(); renderProjects(); renderOverview(); renderPanel(); renderSidebarPanels(); }
function selectProject(projectId) { state.selectedId=projectId;state.pillar='';state.section='';state.checkState='';state.checkSearch='';state.page=1;renderAll(); }
let toastTimer;
function toast(message) { $('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('#toast').hidden=true;},5500); }
function closePopovers() { $$('.popover').forEach(element=>{element.hidden=true;});['notifications','profile'].forEach(name=>$(`#${name}-button`).setAttribute('aria-expanded','false')); }
function showError(error) { $('#dialog-error').textContent=error.message || String(error);$('#dialog-error').hidden=false;$('#dialog-error').scrollIntoView({block:'nearest'}); }
function showDialog(title, content, {wide=false, context=null}={}) { closePopovers();state.formContext=context;$('#dialog-title').textContent=title;$('#dialog-content').innerHTML=content;$('#dialog-error').hidden=true;$('#app-dialog').classList.toggle('dialog-wide',wide);if(!$('#app-dialog').open)$('#app-dialog').showModal(); }
function context(extra={}) { const value=project();return {projectId:value?.id,version:value?.version,...extra}; }
function formProject() { const info=state.formContext,value=state.projects.find(entry=>entry.id===info?.projectId);if(!value||value.version!==info.version)throw new Error('El proyecto cambió mientras editabas. Cierra esta ventana y vuelve a abrirla para no sobrescribir cambios.');return value; }
let savingProject = false;
async function persist(next, previousVersion=null, imported=null) {
  if(!store)throw new Error(startupError);
  savingProject = true;
  try {
  if (!imported) await store.beforeChange(next.id); else await store.assertWritable(next.id);
  store.save(next,previousVersion);state.selectedId=next.id;loadProjects();renderAll();
  try { if(imported)await store.acknowledgeExternal(next.id,imported.name,imported.source);await store.mirror(next); }
  catch(error) { state.fileMessage=error.message;renderStorage();return false; }
  state.fileMessage='';renderStorage();return true;
  } finally { savingProject = false;loadProjects();renderAll(); }
}
