/* Formularios y revisión de importaciones. Solo HTML y APIs nativas. */
const field = (name, label, value = '', type = 'text', required = false) => `<label class="form-field">${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}"${required ? ' required' : ''}${type === 'date' ? ' min="2000-01-01" max="2099-12-31"' : ' maxlength="3000"'}></label>`;
const area = (name, label, value = '', required = false) => `<label class="form-field">${esc(label)}<textarea name="${name}" maxlength="20000"${required ? ' required' : ''}>${esc(value)}</textarea></label>`;
const selectField = (name, label, entries, value = '') => `<label class="form-field">${esc(label)}<select name="${name}">${entries.map(([key, text]) => `<option value="${esc(key)}"${key === value ? ' selected' : ''}>${esc(text)}</option>`).join('')}</select></label>`;
const formActions = (label = 'Guardar cambios') => `<div class="dialog-actions">${actionButton('close-dialog','Cancelar')}<button class="button button-primary" type="submit">${esc(label)}</button></div>`;
const reasonField = value => area('reason', 'Motivo / justificación del registro', value || '', true);
const documentOptions = () => [['','Sin documento vinculado'],...(project()?.documents || []).map(doc=>[doc.id,`${doc.name}${doc.revision ? ` · Rev. ${doc.revision}` : ''}`])];
function evidenceRow(entry = {}) {
  const evidence = { id:CCM.id('ev'),documentId:'',fileName:'',path:'',revision:'',locator:'',quote:'',url:'',...entry };
  const input = (key,label,type='text') => `<label class="form-field">${label}<input data-ev="${key}" type="${type}" value="${esc(evidence[key])}" maxlength="3000"></label>`;
  return `<div class="evidence-edit" data-evidence-id="${esc(evidence.id)}"><div class="panel-heading"><strong>Origen de la información</strong>${actionButton('remove-evidence','Quitar','','text-button')}</div><label class="form-field">Documento registrado<select data-ev="documentId">${documentOptions().map(([key,label])=>`<option value="${esc(key)}"${evidence.documentId===key?' selected':''}>${esc(label)}</option>`).join('')}</select></label><div class="form-columns">${input('fileName','Nombre del archivo o correo')}${input('revision','Revisión del documento')}</div>${input('path','Ruta / subcarpeta')}${input('locator','Página, sección, hoja y celdas, o datos del correo')}<label class="form-field">Extracto que respalda el dato<textarea data-ev="quote" maxlength="20000">${esc(evidence.quote)}</textarea></label>${input('url','Enlace al archivo (opcional)','url')}</div>`;
}
function evidenceEditor(entries=[]) {
  return `<fieldset class="evidence-fieldset"><legend>Evidencia y origen</legend><p class="field-help">Indica archivo, ubicación precisa y extracto. Puedes citar más de una fuente.</p><div class="evidence-editors">${entries.map(evidenceRow).join('')}</div>${actionButton('add-evidence',`${icon('plus')} Agregar evidencia`)}</fieldset>`;
}
function readEvidence(form) {
  return $$('.evidence-edit',form).map(row=>{
    const entry={id:row.dataset.evidenceId};
    $$('[data-ev]',row).forEach(input=>{entry[input.dataset.ev]=input.value.trim();});
    return entry;
  }).filter(entry=>Object.entries(entry).some(([key,value])=>key!=='id'&&value));
}
function showProjectForm(edit=false) {
  const info=edit?project().info:{startDate:CCM.today(),technology:'undetermined',offerStatus:'unreviewed'};
  showDialog(edit?'Editar proyecto':'Nuevo proyecto',`<form id="form-project" class="form-grid"><p class="dialog-description">${edit?'Los cambios de datos generales también quedan registrados en el historial.':'El proyecto inicia con 145 controles sin revisar y sin evidencia, documentos, consultas ni contactos precargados.'}</p><div class="form-columns">${field('client','Cliente final',info.client||'','text',true)}${field('buyer','Comprador / EPC',info.buyer||'')}</div>${field('name','Nombre del proyecto',info.name||'','text',true)}<div class="form-columns">${field('crm','ID CRM / negocio',info.crm||'')}${field('manager','Responsable del proyecto',info.manager||'')}</div>${field('location','Ubicación',info.location||'')}<div class="form-columns">${field('startDate','Fecha de ingreso',info.startDate||'','date',true)}${field('targetDate','Fecha objetivo de oferta',info.targetDate||'','date')}</div>${field('driveUrl','URL de la carpeta de Drive',info.driveUrl||'','url')}${selectField('technology','Tipo de solución',[['undetermined','Por definir'],['ccm','CCM'],['vdf','VDF'],['ccm_vdf','CCM y VDF']],info.technology)}${edit?`${selectField('offerStatus','Condición de oferta',Object.entries(offers).map(([key,[label]])=>[key,label]),info.offerStatus)}${area('offerReason','Criterio técnico/comercial para la condición de oferta',info.offerReason)}${reasonField('')}`:''}${formActions(edit?'Guardar cambios':'Crear proyecto vacío')}</form>`,{wide:true,context:edit?context({form:'project'}):{form:'new-project'}});
}
function showChecklist(itemId) {
  const item=project().checklist.find(entry=>entry.id===itemId);if(!item)return;
  const requirement=`<div class="requirement-box"><strong>${esc(item.label)}</strong><p>${esc(item.criterion)}</p><a href="assets/Requerimientos_minimos_CCM_VDF.pdf#page=${item.page}" target="_blank" rel="noopener">Guía · sección ${item.section} · página ${item.page}</a>${item.critical?'<p class="danger-text">Dato crítico para una oferta firme. «No aplica» requiere justificación.</p>':''}</div>`;
  if(closed(project())) {showDialog(item.label,`${requirement}<p>${badge(...checkStates[item.state])}</p><p class="read-value">${esc(item.value)}</p><p>${esc(item.notes)}</p>${evidenceMarkup(item.evidence)}`,{wide:true});return;}
  showDialog('Actualizar control',`<form id="form-checklist" class="form-grid">${requirement}${selectField('state','Estado',Object.entries(checkStates).map(([key,[label]])=>[key,label]),item.state)}${area('value','Dato encontrado / valor',item.value)}${area('notes','Observaciones, faltantes o justificación de no aplicación',item.notes)}${evidenceEditor(item.evidence)}<label class="toggle-setting"><input type="checkbox" name="manualLock" checked>Proteger este ajuste manual frente a nuevas revisiones de IA</label>${reasonField('')}${formActions()}</form>`,{wide:true,context:context({itemId})});
}
function showDocumentForm(recordId='') {
  const entry=project().documents.find(doc=>doc.id===recordId)||{id:CCM.id('doc'),name:'',path:'',familyId:'',revision:'',url:'',mimeType:'application/pdf',readStatus:'not_reviewed',notes:''};
  showDialog(recordId?'Editar documento':'Registrar documento',`<form id="form-document" class="form-grid">${field('name','Nombre del archivo o asunto del correo',entry.name,'text',true)}${field('path','Ruta relativa completa',entry.path)}<div class="form-columns">${field('familyId','Familia documental (común a sus revisiones)',entry.familyId)}${field('revision','Revisión (0, 1, 2, A, B…)',entry.revision)}</div>${field('url','Enlace al documento',entry.url,'url')}${selectField('mimeType','Formato',[['application/pdf','PDF'],['application/vnd.openxmlformats-officedocument.wordprocessingml.document','DOCX'],['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','XLSX'],['message/rfc822','Correo EML'],['application/vnd.ms-outlook','Correo MSG'],['text/plain','Texto'],['other','Otro']],entry.mimeType)}${selectField('readStatus','Cobertura de lectura',[['not_reviewed','Sin revisar'],['metadata_only','Solo se conocen metadatos'],['read','Contenido leído'],['unreadable','No se pudo leer']],entry.readStatus)}${area('notes','Observaciones / limitaciones de lectura',entry.notes)}${reasonField(recordId?'':'Registro manual del documento.')}${formActions()}</form>`,{wide:true,context:context({recordId:entry.id,original:entry})});
}
function showFileForm(recordId='') {
  const entry=(project().processedFiles||[]).find(file=>file.id===recordId)||CCMFiles.blank(CCM.id('file'),project().info.driveUrl);
  showDialog(recordId?'Editar registro de archivo':'Registrar archivo de Drive',`<form id="form-file" class="form-grid"><p class="dialog-description">Registra metadatos reales del archivo. Guardar su nombre o enlace no significa que su contenido haya sido leído.</p>${field('fileName','Nombre del archivo',entry.fileName,'text',true)}${field('folderUrl','URL de la carpeta raíz del proyecto',entry.folderUrl,'url',true)}${field('path','Ruta relativa, incluyendo subcarpetas y archivo',entry.path,'text',true)}<div class="form-columns">${field('driveFileId','ID del archivo en Drive',entry.driveFileId)}${field('url','Enlace al archivo',entry.url,'url')}</div>${selectField('documentId','Documento / revisión asociado',documentOptions(),entry.documentId)}<div class="form-columns">${field('modifiedTime','Última modificación (ISO 8601)',entry.observed.modifiedTime)}${field('sizeBytes','Tamaño en bytes (vacío si no disponible)',entry.observed.sizeBytes??'','number')}</div>${field('version','Versión informada por Drive (si está disponible)',entry.observed.version)}<div class="form-columns">${selectField('checksumAlgorithm','Algoritmo de la huella',[['','Sin huella'],['md5','MD5'],['sha1','SHA-1'],['sha256','SHA-256']],entry.observed.checksumAlgorithm)}${field('checksum','Huella real del contenido',entry.observed.checksum)}</div><div class="form-columns">${selectField('availability','Disponibilidad',[['present','Presente'],['not_seen','No localizado / acceso incompleto'],['removed','Retirado, confirmado']],entry.availability)}${selectField('processingStatus','Resultado de lectura',[['pending','Pendiente'],['processed','Completa'],['partial','Parcial'],['failed','Error de lectura']],entry.processing.status)}</div><label class="toggle-setting"><input type="checkbox" name="confirmProcessed">Confirmo que acabo de leer y revisar todo el contenido. Guardar estos metadatos como la versión procesada y quitar la solicitud de relectura.</label><p class="field-help">Si solo actualizas metadatos, deja la casilla desmarcada: la lectura anterior conserva su fecha y su versión, y se comparará con los cambios observados.</p>${area('processingNotes','Notas / limitaciones de lectura',entry.processing.notes)}${reasonField('')}${formActions()}</form>`,{wide:true,context:context({original:entry,recordId:entry.id})});
}
function showFileDetails(recordId) {
  const file=(project().processedFiles||[]).find(entry=>entry.id===recordId);if(!file)return;
  const decision=CCMFiles.evaluate(file,project().info.driveUrl);
  showDialog(file.fileName,`<p class="dialog-description">${esc(file.path)}</p><p>${esc(decision.label)} · ${esc(decision.reason)}</p><div class="diff-grid"><div><strong>Última versión procesada</strong><pre>${esc(JSON.stringify({source:file.processing.source,metadata:file.processing.fingerprint,processedAt:file.processing.processedAt,provider:file.processing.provider},null,2))}</pre></div><div><strong>Última observación</strong><pre>${esc(JSON.stringify({folderUrl:file.folderUrl,driveFileId:file.driveFileId,path:file.path,lastSeenAt:file.lastSeenAt,metadata:file.observed},null,2))}</pre></div></div><p class="read-value">${esc(file.processing.notes)}</p>`,{wide:true});
}
function showFileReread(recordId) {
  const file=project().processedFiles.find(entry=>entry.id===recordId);
  showDialog('Solicitar relectura',`<form id="form-file-reread" class="form-grid"><p class="dialog-description">${esc(file.fileName)} se incluirá nuevamente en las próximas instrucciones al chat, aunque sus metadatos no cambien.</p>${reasonField('')}${formActions('Marcar para relectura')}</form>`,{context:context({recordId})});
}
function showRevisionForm(recordId='') {
  const entry=project().revisions.find(value=>value.id===recordId)||{id:CCM.id('chg'),familyId:'',fromRevision:'',toRevision:'',fromDocumentId:'',toDocumentId:'',summary:'',justification:'',justificationStatus:'unknown',impact:'',evidence:[]};
  showDialog('Cambio entre revisiones',`<form id="form-revision" class="form-grid"><p class="dialog-description">Registra lo que cambió entre dos revisiones del mismo documento. Si no encontraste la razón del cambio, indícalo expresamente.</p>${field('familyId','Familia / nombre del documento',entry.familyId,'text',true)}<div class="form-columns">${selectField('fromDocumentId','Documento de origen',documentOptions(),entry.fromDocumentId)}${selectField('toDocumentId','Documento de destino',documentOptions(),entry.toDocumentId)}</div><div class="form-columns">${field('fromRevision','Revisión de origen',entry.fromRevision,'text',true)}${field('toRevision','Revisión de destino',entry.toRevision,'text',true)}</div>${area('summary','Cambios observados (valores anterior y nuevo)',entry.summary,true)}${selectField('justificationStatus','Origen de la justificación',[['unknown','No se encontró justificación'],['documented','Documentada en una fuente'],['inferred','Inferencia, no confirmada']],entry.justificationStatus)}${area('justification','Justificación del cambio',entry.justification)}${area('impact','Impacto en alcance, precio, plazo o configuración',entry.impact)}${evidenceEditor(entry.evidence)}${reasonField(recordId?'':'Registro de comparación entre revisiones.')}${formActions()}</form>`,{wide:true,context:context({recordId:entry.id,original:entry})});
}
function showTeamForm(recordId='') {
  const entry=project().team.find(person=>person.id===recordId)||{id:CCM.id('person'),name:'',role:'',company:'',phone:'',email:'',notes:''};
  showDialog(recordId?'Editar integrante':'Agregar integrante',`<form id="form-team" class="form-grid">${field('name','Nombre',entry.name,'text',true)}<div class="form-columns">${field('role','Cargo',entry.role)}${field('company','Empresa',entry.company)}</div><div class="form-columns">${field('phone','Teléfono',entry.phone,'tel')}${field('email','Correo',entry.email,'email')}</div>${area('notes','Origen del contacto / observaciones',entry.notes)}${reasonField(recordId?'':'Registro de integrante del equipo.')}${formActions()}</form>`,{context:context({recordId:entry.id,original:entry})});
}
function showQueryForm(itemId='') {
  const item=project().checklist.find(value=>value.id===itemId);
  showDialog('Nueva consulta',`<form id="form-query" class="form-grid">${field('title','Asunto',item?`Confirmar: ${item.label}`:'','text',true)}${area('question','Consulta concreta al cliente o tercero','',true)}${field('assignedTo','Responsable / destinatario','')}${selectField('relatedChecklistId','Control relacionado',[['','Sin control específico'],...project().checklist.map(control=>[control.id,`${control.id} · ${control.label}`])],itemId)}${evidenceEditor()}${formActions('Registrar consulta abierta')}</form>`,{wide:true,context:context()});
}
function showQueryDetail(queryId) {
  const query=project().queries.find(entry=>entry.id===queryId);if(!query)return;
  showDialog(query.title,`<div class="query-detail"><p>${badge(query.status==='closed'?'Cerrada':'Abierta',query.status==='closed'?'green':'amber')}</p><p class="read-value">${esc(query.question)}</p><p class="muted">Responsable: ${esc(query.assignedTo||'Sin asignar')} · ${formatTime(query.createdAt)}</p>${evidenceMarkup(query.evidence)}${query.status==='closed'?`<div class="closure-summary"><strong>Resolución · ${formatTime(query.closedAt)}</strong><p>${esc(query.resolution)}</p></div>`:''}<h3>Seguimiento</h3>${query.messages.map(message=>`<article class="message-card"><div class="panel-heading"><strong>${esc(message.author)}</strong><time>${formatTime(message.at)}</time></div><p>${esc(message.body)}</p>${message.evidence.length?evidenceMarkup(message.evidence):''}</article>`).join('')||empty('Sin seguimientos registrados.')}${closed(project())?'':`<form id="form-query-message" class="form-grid">${query.status==='open'?selectField('transition','Acción',[['message','Agregar seguimiento'],['closed','Resolver y cerrar consulta']],'message'):'<input type="hidden" name="transition" value="reopened">'}${area('body',query.status==='open'?'Seguimiento / resolución':'Motivo de reapertura','',true)}${evidenceEditor()}${formActions(query.status==='open'?'Guardar seguimiento':'Reabrir consulta')}</form>`}</div>`,{wide:true,context:context({queryId})});
}
function showNoteForm() {showDialog('Agregar registro al historial',`<form id="form-note" class="form-grid">${area('body','Decisión, acuerdo o comentario','',true)}${evidenceEditor()}${formActions('Guardar registro')}</form>`,{wide:true,context:context()});}
function showIdentity() {showDialog('Responsable de cambios',`<form id="form-identity" class="form-grid"><p class="dialog-description">Este nombre se registra en las próximas modificaciones. Los autores de los registros anteriores se conservan.</p>${field('actor','Nombre',state.actor,'text',true)}${formActions('Guardar nombre')}</form>`);}
function showCalendar(year=Number(CCM.today().slice(0,4))) {
  const value=project(),coverage=value.calendar.coverage.find(entry=>entry.year===year),holidays=value.calendar.holidays.filter(entry=>Number(entry.date.slice(0,4))===year).sort((a,b)=>a.date.localeCompare(b.date));
  const years=[...new Set([year-1,year,year+1,...value.calendar.coverage.map(entry=>entry.year)])].filter(n=>n>=2000&&n<2100).sort();
  showDialog('Calendario de días hábiles',`<p class="dialog-description">Calendario de este proyecto. Se excluyen el día inicial, sábados, domingos y las fechas de esta lista. Agrega los feriados regionales, locales o internos que correspondan.</p><div class="calendar-toolbar"><label>Año <select id="calendar-year">${years.map(n=>`<option${n===year?' selected':''}>${n}</option>`).join('')}</select></label>${badge(coverage?.complete?'Año verificado':'Año pendiente',coverage?.complete?'green':'amber')}${closed(value)?'':actionButton('holiday-form',`${icon('plus')} Agregar feriado`)}</div>${coverage?`<p class="field-help">Fuente: ${coverage.source.startsWith('http')?link(coverage.source,'Consultar calendario'):esc(coverage.source)} · verificado ${formatDate(coverage.verifiedAt)}</p>`:''}<div class="calendar-list">${holidays.map(holiday=>`<div><time>${formatDate(holiday.date)}</time><span>${esc(holiday.name)}<small>${esc(({national:'Nacional',regional:'Regional',local:'Comunal',company:'Interno'})[holiday.scope])}</small></span>${closed(value)?'':actionButton('remove-holiday','Quitar',holiday.id,'text-button')}</div>`).join('')||empty('No hay feriados registrados para este año.')}</div>${closed(value)?'<p class="field-help">El cierre conserva su calendario y su duración. Reabre el proyecto para modificarlo.</p>':`<details class="calendar-verification"><summary>Verificar o completar el año ${year}</summary><form id="form-calendar-coverage" class="form-grid"><input type="hidden" name="year" value="${year}">${field('source','Fuente oficial consultada / referencia',coverage?.source||'','text',true)}<label class="toggle-setting"><input type="checkbox" required name="verified">Confirmo que revisé los feriados aplicables al proyecto para este año.</label>${reasonField('Verificación del calendario anual.')}${formActions('Marcar año verificado')}</form></details>`}`,{wide:true,context:context({year})});
}
function showHolidayForm() {showDialog('Agregar feriado',`<form id="form-holiday" class="form-grid">${field('date','Fecha','','date',true)}${field('name','Nombre del feriado','','text',true)}${selectField('scope','Alcance',[['national','Nacional'],['regional','Regional'],['local','Comunal'],['company','Interno de la empresa']],'national')}${field('source','Fuente / referencia de respaldo','','text',true)}${reasonField('Incorporación de feriado al calendario del proyecto.')}${formActions('Guardar feriado')}</form>`,{context:context()});}
function showRemoveHoliday(holidayId) {const holiday=project().calendar.holidays.find(entry=>entry.id===holidayId);showDialog('Quitar feriado',`<form id="form-remove-holiday" class="form-grid"><p class="dialog-description">${formatDate(holiday.date)} · ${esc(holiday.name)}. El cambio afectará el conteo del proyecto abierto y quedará en el historial.</p>${reasonField('')}${formActions('Quitar del calendario')}</form>`,{context:context({holidayId})});}
function showCloseProject() {
  const value=project(),calculation=CCM.elapsed(value);
  showDialog('Cerrar propuesta',`<form id="form-close-project" class="form-grid"><p class="dialog-description">Se guardarán el estado final, el historial, las referencias y una copia del calendario utilizado. El proyecto quedará disponible en «Cerrados».</p><div class="close-counter" id="close-counter">${calculation?`${calculation.days} días hábiles${calculation.complete?'':' · calendario incompleto'}`:'Define primero la fecha de ingreso.'}</div>${field('date','Fecha real de cierre',CCM.today(),'date',true)}${selectField('outcome','Resultado',Object.entries(outcomes),'sent')}${reasonField('')}<p class="field-help">${value.queries.filter(query=>query.status==='open').length} consultas siguen abiertas. El cierre del proyecto conserva sus estados y no inventa resoluciones. El JSON contiene las referencias; conserva también los archivos originales de Drive.</p>${formActions('Cerrar y exportar JSON')}</form>`,{context:context()});
}
function showReopenProject() {showDialog('Reabrir proyecto',`<form id="form-reopen-project" class="form-grid"><p class="dialog-description">El cierre anterior, sus días hábiles y su calendario permanecerán en el historial. El conteo activo continuará desde el ingreso original.</p>${reasonField('')}${formActions('Reabrir proyecto')}</form>`,{context:context()});}
function showAIWorkflow() {
  const value=project();
  const message=`El dashboard está en D:\\DashboardMichelle. Lee GEMINI.md y actualiza el proyecto "${value.info.name}" (ID ${value.id}) en la carpeta de JSON "${store.directoryName||'projects'}". Usa tools/project-pipeline.js para preparar y aplicar la revisión. Los antecedentes están en ${value.info.driveUrl||'[completar URL de Drive]'}. Revisa subcarpetas, compara los archivos procesados y lee solo los nuevos, modificados o pendientes. Conserva las fuentes, revisiones, consultas, ajustes manuales e historial. Si no tienes acceso a Drive o a un formato, declara la limitación sin inventar resultados. Al terminar aplica el JSON y reporta lo leído, reutilizado y pendiente.`;
  showDialog('Actualizar proyecto con un agente',`<div class="ai-workflow"><p class="dialog-description">El agente lee los antecedentes y actualiza el JSON del proyecto. El dashboard carga el resultado automáticamente.</p><ol><li>Vincula la carpeta <strong>projects</strong> de esta aplicación y registra la URL de Drive.</li><li>Abre Gemini CLI u otro agente con acceso a esta carpeta y a los documentos.</li><li>Envía este mensaje. Ajusta las rutas si moviste la aplicación o elegiste otra carpeta de JSON.</li></ol><textarea id="pipeline-prompt" class="pipeline-prompt" aria-label="Mensaje para el agente">${esc(message)}</textarea>${actionButton('copy-pipeline','Copiar mensaje para el agente','','button button-primary')}<p class="field-help">${store.connected?`Carpeta vinculada: ${esc(store.directoryName)}. Recarga cada 5 segundos.`:'Falta vincular la carpeta: por ahora el proyecto solo está en el navegador.'} El agente debe poder escribir archivos locales y acceder a los antecedentes; el enlace de Drive por sí solo no habilita ese acceso.</p><a href="INICIO_GEMINI/00_EMPEZAR_AQUI.md" target="_blank" rel="noopener">Guía de inicio</a><details><summary>Si trabajas desde un chat web</summary><p>Usa el intercambio de archivos con revisión manual.</p>${actionButton('manual-ai-workflow','Exportar / importar con revisión manual')}</details></div>`,{wide:true,context:context()});
}
function showManualAIWorkflow() {
  const value=project();
  showDialog('Revisión con Gemini o ChatGPT',`<div class="ai-workflow"><p class="dialog-description">Trabaja en tu chat habitual con la carpeta autorizada. Aquí preparas el JSON y revisas los cambios devueltos.</p><div class="workflow-step"><b>1</b><div><h3>Prepara el JSON padre</h3><p>Exporta la versión actual. No hagas cambios en el dashboard hasta recibir la revisión, o tendrás que exportar nuevamente.</p>${actionButton('export-review',`${icon('document')} Descargar JSON para revisión`,'','button button-primary')}</div></div><div class="workflow-step"><b>2</b><div><h3>Entrega las instrucciones al chat</h3><p>Adjunta el JSON y habilita los documentos de Drive. El chat debe devolver el JSON completo con evidencias y cobertura de lectura.</p>${actionButton('copy-prompt','Copiar instrucciones')}<details><summary>Ver instrucciones</summary><textarea id="ai-prompt" readonly aria-label="Instrucciones para el chat">${esc(CCMReviewPrompt(value))}</textarea></details></div></div><div class="workflow-step"><b>3</b><div><h3>Importa y revisa las diferencias</h3><p>Los ajustes manuales estarán desmarcados. Tú eliges qué aceptar; los valores anteriores se conservan.</p>${actionButton('import','Importar JSON revisado')}</div></div><p class="field-help">${value.info.driveUrl?link(value.info.driveUrl,'Abrir carpeta de antecedentes'):'Todavía no registraste la URL de Drive. Puedes hacerlo en «Editar proyecto».'}</p></div>`,{wide:true,context:context()});
  const tracked=CCMFiles.summary(value);
  $('#dialog-content').insertAdjacentHTML('afterbegin',`<div class="incremental-summary"><strong>Revisión incremental</strong><br>${tracked.total} archivos registrados · ${tracked.skip} sin cambios según el último inventario · ${tracked.read+tracked.verify} por leer o verificar.<br>El chat actualizará primero los metadatos de Drive y podrá omitir el contenido que siga igual. La fecha de su lectura anterior se conserva.</div>`);
}
function showReviewPreview(review) {
  const collectionLabel={info:'Proyecto',checklist:'Checklist',documents:'Documentos',revisions:'Revisiones',queries:'Consultas',team:'Equipo',processedFiles:'Archivo procesado'};
  showDialog('Revisar cambios del JSON',`<form id="form-apply-review" class="form-grid"><p class="dialog-description">${esc(review.provider)} · ${review.changes.length} cambios propuestos sobre JSON v${review.baseVersion}. Los ajustes protegidos requieren selección explícita.</p><div class="coverage-box"><p><strong>Cobertura declarada:</strong> ${review.analysis.coverage.read} / ${review.analysis.coverage.discovered} archivos leídos.</p><p>${esc(review.analysis.summary)}</p><p>${esc(review.analysis.coverage.notes)}</p>${review.analysis.coverage.unreadable.length?`<p class="danger-text">Sin leer: ${review.analysis.coverage.unreadable.map(esc).join(', ')}</p>`:''}</div>${review.warnings.length?`<div class="form-notice">${review.warnings.map(esc).join('<br>')}</div>`:''}<div class="review-changes">${review.changes.map(change=>`<article class="review-change"><label><input type="checkbox" name="change" value="${esc(change.key)}"${change.locked?'':' checked'}><strong>${esc(collectionLabel[change.collection])} · ${esc(change.collection==='info'?infoLabels[change.id]:change.label)}</strong>${change.locked?'<span class="protected-badge">Ajuste manual / dato existente</span>':''}</label><details><summary>Comparar valores y evidencia</summary><div class="diff-grid"><div><span>Actual</span><pre>${esc(JSON.stringify(change.before,null,2))}</pre></div><div><span>Propuesto</span><pre>${esc(JSON.stringify(change.after,null,2))}</pre></div></div></details></article>`).join('')||empty('El chat no propuso cambios. Puedes registrar la revisión y su cobertura.')}</div>${formActions('Aplicar selección y registrar revisión')}</form>`,{wide:true,context:context()});
  $('#form-apply-review .coverage-box').insertAdjacentHTML('beforeend',`<p><strong>Reutilizados sin leer nuevamente:</strong> ${review.analysis.coverage.reused||0}</p>`);
  if(review.changes.some(change=>change.collection==='processedFiles'))$('#form-apply-review').insertAdjacentHTML('afterbegin','<p class="field-help">Si aceptas registros de lectura pero descartas cambios de contenido, las nuevas lecturas se marcarán para revisión antes de reutilizar sus resultados.</p>');
}
async function receiveJSON(source,name) {
  const incoming=CCM.parseJSON(source);CCM.validateProject(incoming);
  state.pendingImport={incoming,source,name};
  const existing=state.projects.find(value=>value.id===incoming.id);
  if(incoming.reviewContext) {
    if(!existing)throw new Error('Importa primero el JSON padre original de este proyecto. Una revisión de IA se compara contra su versión guardada.');
    selectProject(existing.id);state.review=await CCM.compareReview(existing,incoming);showReviewPreview(state.review);return;
  }
  if(existing&&CCM.same(existing,incoming)){toast('Este proyecto ya está guardado con el mismo contenido.');return;}
  if(existing) {
    const sharesHistory=incoming.history.length>existing.history.length&&existing.history.every((event,index)=>CCM.same(event,incoming.history[index]));
    if(incoming.version<=existing.version||!sharesHistory)throw new Error('El archivo tiene otra línea de cambios o una versión anterior. No se reemplazará el historial. Para una revisión de IA usa el JSON de «Preparar revisión IA».');
  }
  showDialog(existing?'Restaurar versión posterior':'Importar proyecto',`<p class="dialog-description">${esc(incoming.info.client||'Sin cliente')} – ${esc(incoming.info.name||'Sin nombre')}</p><dl class="detail-list"><div><dt>Versión</dt><dd>${incoming.version}</dd></div><div><dt>Contenido</dt><dd>${incoming.checklist.length} controles · ${incoming.documents.length} documentos · ${incoming.queries.length} consultas · ${incoming.history.length} registros históricos</dd></div><div><dt>Estado</dt><dd>${closed(incoming)?'Cerrado, con calendario y duración conservados':'En curso'}</dd></div></dl><div class="dialog-actions">${actionButton('close-dialog','Cancelar')}${actionButton('confirm-import',existing?'Restaurar versión':'Importar proyecto','','button button-primary')}</div>`,{context:{projectId:incoming.id,version:existing?.version??null}});
}
